version: "3.7"
services:
  client:
    image: akm4545/opgg_front
    container_name: opgg_front
    ports:
      - "3000:3000"


  # nginx:
  #   depends_on:
  #     - client
  #   restart: always
  #   build:
  #     dockerfile: Dockerfile
  #     context: ./nginx
  #   ports:
  #     - "80:80"