name: Docker
on:
  push:
    branches: [test]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # 도커 빌드 관련 셋업
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      # 내 도커허브 로그인
      - name: web docker build and push
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_REPO }}/opgg_front ./opgg_front
          docker push ${{ secrets.DOCKER_REPO }}/opgg_front
      
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: root
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          ##key: ${{ secrets.KEY }}
          script: |
            sudo docker stop opgg_front
            sudo docker rm -f opgg_front
            sudo docker pull ${{ secrets.DOCKER_REPO }}/opgg_front
            cd ../
            cd var/
            cd opgg_front/
            docker-compose up -d
            docker image prune -f
